### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by ElGecko76** [braintree/braintree_php_example#10]
Hello,

I have an error 404 after submitting the form (credit card, the expiration date and the amount).

Can you help me please ?

Thanks in advance.

**Comment by jackellenberger** [comment]
Hi @ElGecko76,

Can you give a bit of information about what changes you have made to the example repository, and what your configuration looks like? 

With no modifications (aside from entering my .env information), I am seeing an "Unexpected EOF" warning, but no 404's. Could you attach the output of your local server when you try to access `http://localhost:3000`?

**Comment by ElGecko76** [comment]
Hi @jackellenberger My OS is MAC OS and my host is Hostinger.

I installed the required libraries with composer (composer install), I completed example.env with my keys and I renamed the file to .env 

I have not used a local server with > http://localhost:3000

**Comment by jackellenberger** [comment]
Hey @ElGecko76,

Before deploying the example code, why not try it out on your local machine? Run `php -S localhost:3000 -t public_html` from the repository root, then access it in your browser at `http://localhost:3000`. 

If you're having trouble specifically deploying to Hostinger, you could contact our support team at support@getbraintree.com, although Hostinger's support forums may be more useful. 

I'm going to close this issue, but feel free to reopen it if you run into any problems with the repository itself.

**Comment by ElGecko76** [comment]
Hi @jackellenberger, 

Because in the futur I would like to propulse it on the web and not in local :/ but I will be testing it

**Comment by ElGecko76** [comment]
![capture d ecran 2016-08-19 a 09 20 46](https://cloud.githubusercontent.com/assets/19478137/17802123/a40ee53a-65ee-11e6-8960-16f2e5b17ae9.png)

**Comment by ElGecko76** [comment]
The problem is solved, I was in Production and not in Sandbox ! Sorry for the inconvenience and thanks you for your answers !
