### ISSUE TITLE
should include option 'submitForSettlement' in Braintree_Transaction::sale() method

### ISSUE THREAD

**Issue by phannam1412** [braintree/braintree_php_example#11]
hello, thank for the great example.

One small thing, can you include option 'submitForSettlement' in the code as follows:

$result = Braintree_Transaction::sale([
  'amount' => '10.00',
  'paymentMethodNonce' => nonceFromTheClient,
  'options' => [
    'submitForSettlement' => True
  ]
]);

**Comment by mtmarsh3** [comment]
Hi @phannam1412,

Thanks for the suggestion! We agree that this is a worthwhile change for the repository. If you make a pull request with the update, we'll merge it in!

**Comment by DavidWard1980** [comment]
$result=Braintree_Transaction::sale([
 'amount'='0.00',
'PaymentMethodnonce=>nonceFromTheClient,
  'options'=> [
'submitForSettlement=>True
]
]);

Yes that would be nice!!

**Comment by pprevalon** [comment]
@phannam1412 Braintree suggest that, mainly because you dont have to go into the braintree and manually submitting settlements which can be time consuming

**Comment by mtmarsh3** [comment]
Thanks @phannam1412 ! Your PR has been merged, so I'm going to close this issue.
