### ISSUE TITLE
Missing autoload.php

### ISSUE THREAD

**Issue by rainerbrunotte** [braintree/braintree_php_example#14]
It seems that the index.php file is looking for the "require 'vendor/autoload.php';" file, but it is not available in the ZIP, thus I cannot get the script to work?

**Comment by jdlc** [comment]
Hi @rainerbrunotte,
It looks like you weren't able to install the dependencies properly, or else your vendor/autoload.php file would have been generated. After installing composer locally, did you run `php composer.phar install` or `composer install` if you installed it globally?

**Comment by rainerbrunotte** [comment]
Hi @jdlc,
I moved the files to the server via FTP

**Comment by jdlc** [comment]
Please contact [Braintree support](https://support.braintreepayments.com) and we can help walk you through setting up the example integration. Closing this issue.
