### ISSUE TITLE
Could not open input file: composer.phar

### ISSUE THREAD

**Issue by haziqazmi** [braintree/braintree_php_example#16]
I have already download composer version 1.3.1 in C:\wamp\bin\php\php5.4.12\php.exe and trying to run composer by insert this command  "php composer.phar install" in command prompt and output is "Could not open input file: composer.phar"

C:\wamp\www\braintree_php_example-master>php composer.phar install
Could not open input file: composer.phar

**Comment by jaypatel512** [comment]
Hey @haziqazmi !

The composer.phar file needs to be present at the current location where you plan to run the above command. In your case, `C:\wampp\www\braintree_php_example-master`. 

You can chose to follow installation instruction for composer at: https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx

**Comment by jaypatel512** [comment]
Please re-open the issue if you are still having the issue.
