### ISSUE TITLE
Notice: Undefined index: payment_method_nonce in C:\wamp\www\braintree_php_example-master\public_html\checkout.php on line 5

### ISSUE THREAD

**Issue by haziqazmi** [braintree/braintree_php_example#17]
I have already done the composer part and able to launch  localhost:3000

![image](https://cloud.githubusercontent.com/assets/21188222/22305434/8a426b8a-e376-11e6-87fd-0d9c9ddf0aab.png)

After inserted the amount in the text field and click test transaction button, an error occur as below in checkout.php at line 5

![image](https://cloud.githubusercontent.com/assets/21188222/22305564/f3ec2256-e376-11e6-9404-c18ce242c011.png)

hope you can help me,
thank

**Comment by bluk** [comment]
@haziqazmi You will need to add your merchant credentials to your environment. Please see step 3 in the [Setup Instructions](https://github.com/braintree/braintree_php_example#setup-instructions).
