### ISSUE TITLE
How to integrate recurring payment in this provided example?

### ISSUE THREAD

**Issue by ramdoss-anubavam** [braintree/braintree_php_example#23]
### General information

* Language  PHP

### Issue description

How to integrate recurring payment in this provided example?

**Comment by bluk** [comment]
See the [Recurring Billing documentation](https://developers.braintreepayments.com/guides/recurring-billing/overview). Specifically, the [Creating Subscriptions page](https://developers.braintreepayments.com/guides/recurring-billing/create/php) and [Managing Subscriptions page](https://developers.braintreepayments.com/guides/recurring-billing/manage/php) have code snippets that may be helpful.

If you need more specific help, please reach out to [Braintree Support](https://developers.braintreepayments.com/forms/contact).
