### ISSUE TITLE
Is it possible for result success to be true and transaction to be null ?

### ISSUE THREAD

**Issue by ashtonzheng** [braintree/braintree_php_example#25]
checkout.php

```
if ($result->success || !is_null($result->transaction)) {
    $transaction = $result->transaction;
    header("Location: transaction.php?id=" . $transaction->id);
}
```

I encountered an issue where the result was true and result transaction is empty in production server and it only happens once in awhile.

**Comment by crookedneighbor** [comment]
@ashtonzheng I would contact our support team about this issue. They will be able to help you. https://developers.braintreepayments.com/forms/contact
