### ISSUE TITLE
No payment nonce available with PayPal

### ISSUE THREAD

**Issue by ShaunDychko** [braintree/braintree_php_example#27]
### General information

* Environment: sandbox
* Language, language version, and OS: PHP 5.6.3 on macOS 10.12.6

### Issue description

A payment nonce is not created when adding PayPal as a payment method, despite a payment nonce being created when adding a credit card. Screenshots attached showing the browser console output. I forked this repo to add the console.log and comment out the form submit, which you can see at: https://github.com/ShaunDychko/braintree_php_example/commit/2e44152f6023394832810f9dc01e409da6e1586d.

How do you explain the lack of a payment nonce with PayPal? Am I missing something, or otherwise this means the Drop-in UI in it's current version isn't supporting PayPal?

<img width="1567" alt="braintree-paypal-no-nonce" src="https://user-images.githubusercontent.com/235214/30253427-a585da14-9639-11e7-9691-3a575882a225.png">
<img width="1563" alt="braintree-credit-card-nonce" src="https://user-images.githubusercontent.com/235214/30253426-a5858334-9639-11e7-9d5a-24490cb2dc12.png">

**Comment by lilaconlee** [comment]
You're right, that's definitely unexpected. I had no issue getting a nonce from PayPal using your fork with my sandbox account, which I tested on Chrome and using PHP 5.4.45. 

I would recommend working with [Braintree support](https://www.braintreepayments.com/contact) who can make sure nothing is wrong with your PayPal settings in your merchant account.

**Comment by ShaunDychko** [comment]
Thank you very much for your response, and I apologize since I had a misunderstanding. I mistakenly expected the nonce after adding the PayPal payment method, but, naturally, the nonce is not expected until clicking "Test Transaction". The nonce shows up as expected!

**Comment by arjit360** [comment]
where to link paypal sandbox ??
