### ISSUE TITLE
trying to processs payment

### ISSUE THREAD

**Issue by lammar2315** [braintree/braintree_php_example#29]
### General information

* Environment: 
* Language, language version, and OS: 

### Issue description

[paypal_cert_pem.txt](https://github.com/braintree/braintree_php_example/files/1512650/paypal_cert_pem.txt)

**Comment by bluk** [comment]
Can you please describe your issue? You can also contact [Braintree Support](https://developers.braintreepayments.com/forms/contact) if needed.

**Comment by jaypatel512** [comment]
Closing this based on inactivity. Please reach out to Braintree Support for any integration questions.

**Comment by lammar2315** [comment]
The issue is not releasing my money or assets to PayPal
