### ISSUE TITLE
production transaction error  at Uncaught exception 'Braintree\Exception\Authorization 

### ISSUE THREAD

**Issue by vickygillsf** [braintree/braintree_php_example#36]
### General information

* Environment: Production
* Language, language version, and OS: PHP SDK on Godaddy Server
As i tested it on sandbox its working fine but when i was going to test it on production i got this error. 

`Fatal error: Uncaught exception 'Braintree\Exception\Authorization' in bt-new/vendor/braintree/braintree_php/lib/Braintree/Util.php:59 Stack trace: #0 bt-new/vendor/braintree/braintree_php/lib/Braintree/Http.php(50): Braintree\Util::throwStatusCodeException(403) #1 /bt-new/vendor/braintree/braintree_php/lib/Braintree/TransactionGateway.php(489): Braintree\Http->post('/merchants/jbdd...', Array) #2 /bt-new/vendor/braintree/braintree_php/lib/Braintree/TransactionGateway.php(48): Braintree\TransactionGateway->_doCreate('/transactions', Array) #3 /bt-new/vendor/braintree/braintree_php/lib/Braintree/TransactionGateway.php(300): Braintree\TransactionGateway->create(Array) #4 /bt-new/public_html/checkout.php(123): Braintree\TransactionGateway->sale(Array) #5 {main} thrown in/bt-new/vendor/braintree/braintree_php/lib/Braintree/Util.php on line 59`

**Comment by crookedneighbor** [comment]
My guess is either that you are using a test card instead of a real credit card in production, or your API user is not authorized to make transactions. Either way, you'll need to contact our support team about this. https://articles.braintreepayments.com/forms/contact
