### ISSUE TITLE
PHP 7.2 "Choose a way to pay" box is missing on index.php

### ISSUE THREAD

**Issue by dchao5** [braintree/braintree_php_example#37]
### General information

* Environment: Sandbox
* Language, language version, and OS: PHP 7.2 running on macOS High Sierra 10.13.3

### Issue description

I followed the Setup Instructions in README.md 1-4 and am successfully presented with "Hi, Let's test a transaction" index.php page. However, there is only an Amount box (default $10) ("Choose a way to pay" box is missing). Clicking 'Test Transaction' gives the error 

> Error: 91508: Cannot determine payment method.

Screenshot with PHP 7.2:
<img width="1278" alt="screen shot 2018-04-02 at 4 04 17 pm" src="https://user-images.githubusercontent.com/20862506/38218641-b6eab256-368f-11e8-9a40-bed545357963.png">

Downgrading to PHP <7.2 successfully shows the "Choose a way to pay" box below the Amount box.  

Screenshot with PHP 7.1.14:
<img width="1279" alt="screen shot 2018-04-02 at 4 03 43 pm" src="https://user-images.githubusercontent.com/20862506/38218637-b15fd4c4-368f-11e8-9789-53dd272d1ec7.png">

#### Additional information:
When I am running the internal PHP server with PHP 7.2, it keeps throwing:
> PHP Deprecated:  Function create_function() is deprecated in /Users/projects/braintree_php_example/vendor/braintree/braintree_php/lib/Braintree/Util.php on line 203

### Temporary proposed solution
We could update composer.json from:
```
  "require" : {
   ...
    "php": ">=5.2.1",
   ...
  },
```
to:
```
  "require" : {
   ...
    "php": ">=5.2.1 <7.2",
   ...
  },
```

Hope this makes sense!
   - Dan

**Comment by crookedneighbor** [comment]
This was [fixed in braintree_php v3.26.0](https://github.com/braintree/braintree_php/blob/master/CHANGELOG.md#3260) and we just never upgraded the sdk in the repo.

I've opened a PR at #38 to do that and include explicit testing for php v7.2 in the Travis build.

**Comment by crookedneighbor** [comment]
This is fixed on master now. Want to give it a try?

**Comment by dchao5** [comment]
Confirmed working for me, with no errors, with PHP 7.2.3. Thank you!
