### ISSUE TITLE
file missing 

### ISSUE THREAD

**Issue by agan116** [braintree/braintree_php_example#42]
### General information

* Environment:  this issue in Sandbox 
* Language, language version, and OS: 
*Failed opening required '../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/braintree/includes/braintree_init.php
 
### Issue description

require_once(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/braintree/includes/braintree_init.php on line 3

**Comment by crookedneighbor** [comment]
How are you installing the library? Are you using composer?

**Comment by crookedneighbor** [comment]
My best guess is that you missed step 2: https://github.com/braintree/braintree_php_example#setup-instructions

Going to close this now, but feel free to comment here if you're still having issues.
