### ISSUE TITLE
Integrate recurring subscription

### ISSUE THREAD

**Issue by jamminjames** [braintree/braintree_php_example#45]
### General information

* Environment: Sandbox 
* Language, language version, and OS: PHP and js on a Windows Xampp server.

### Issue description

See below.

**Comment by jamminjames** [comment]
I read the [closed issue on this here](https://github.com/braintree/braintree_php_example/issues/23), and have read the recurring subscription guide at Braintree. I have this example code working for a simple transaction, but I want to be able to have the customer start a recurring subscription, and don't see how to get the paymentMethodToken. As per the [Braintree guide](https://developers.braintreepayments.com/guides/recurring-billing/create/php), I am using this code:
```
$result = $gateway->subscription()->create([
  'paymentMethodToken' => 'the_token',
  'planId' => 'silver_plan'
]);
```
...dropping in my own created plan id. However, I don't understand how to get the paymentMethodToken for the newly created subscription, so we can go on to do the transaction, and let the customer pay for it immediately. The provided code returns an error, since the token is not provided. ("Error: 91903: Payment method token is invalid.")

I am testing this in our sandbox, of course.

Thanks for any help.

**Comment by Epreuve** [comment]
@jamminjames It sounds like you're skipping the step to create a payment method token.  The payment method nonce generated by the example is a single use representation of a tokenized payment, while a payment method token is created using a nonce, and is used to charge a customer's payment method in a future transaction without requiring them to re-enter their credentials, whether that's a subscription, or a one-off transaction.

You'll want to make sure you're using the payment method nonce generated by the checkout form to first [create a customer with a payment method](https://developers.braintreepayments.com/guides/customers/php#create-with-payment-method) or [add a payment method to an existing customer](https://developers.braintreepayments.com/guides/payment-methods/php#create), then use the payment method token representing the now [vaulted](https://articles.braintreepayments.com/control-panel/vault/overview) payment method in the subscription create call.

If you have any further questions, reach out to [Braintree support](https://help.braintreepayments.com/) and they should be able to help get this solved with you.

**Comment by jamminjames** [comment]
I've got that working, now, how do you finalize the transaction after doing that? When I try:
```
$result = $gateway->transaction()->sale([
    'amount' => $amount,
    'paymentMethodNonce' => $nonce,
    'options' => [
        'submitForSettlement' => true
    ]
]);
```
... I get an error that you can't use the nonce twice. Without it, I get "Cannot determine payment method." 

This is the full code I'm trying:
```
$result = $gateway->customer()->create([
    'firstName' => 'Joe',
    'lastName' => 'Smo',
    'company' => 'Smo Co.',
    'paymentMethodNonce' => $nonce
	]);
	if ($result->success) {
		echo($result->customer->id);
		echo($result->customer->paymentMethods[0]->token);
		$pymtToken=$result->customer->paymentMethods[0]->token;
		} else {
			foreach($result->errors->deepAll() AS $error) {
				echo($error->code . ": " . $error->message . "\n");
			}
		}

	$result = $gateway->subscription()->create([
	'paymentMethodToken' => $pymtToken,
	'planId' => $planId,
	'options' => ['startImmediately' => true]
	]);
	
	$result = $gateway->transaction()->sale([
    'amount' => $amount,
    'paymentMethodNonce' => $nonce,  // what to do here?
    'options' => [
        'submitForSettlement' => true
    ]
]);
```

**Comment by Epreuve** [comment]
Like I mentioned, a payment method nonce is single use, so when you create a customer with a payment method, it's consumed.

That being said, is your intent to charge your customer twice?  When you create a subscription, unless there is a trial period or a future billing date, it will immediately charge the customer.  Attempting to create a transaction after a subscription would result in two charges to the customer.

If you do have a future billing date or a trial period on the subscription, or would still like to charge the customer twice (once when the subscription is create and once in the transaction) then you can replace `paymentMethodNonce` with `paymentMethodToken` within the `sale(..)` call and use the payment method token from the customer `create(..)` call to create the transaction.

**Comment by jamminjames** [comment]
Ok. But, when I leave out the transaction section, I get the error about no transaction id:

"Fatal  error: Uncaught InvalidArgumentException: expected transaction id to be  set in  C:\xampp\apps\wordpress\subs.ht.new\vendor\braintree\braintree_php\lib\Braintree\TransactionGateway.php  on line 507"

...and in the url, it's missing the id (http://localhost/transaction.php?id=)

**Comment by Epreuve** [comment]
If you change the behavior of the example to use subscriptions instead of transactions, you'll need to adjust the result handling code as well.  Naturally, if you remove the code that creates a transaction, you'll need to adjust the snippet here to instead handle the subscription.

Since this isn't an issue with the example itself and is more so a question of building your integration, any follow up questions should be sent to [Braintree support](https://help.braintreepayments.com/) instead.

**Comment by jamminjames** [comment]
Ok, thanks for your help!
