### ISSUE TITLE
Integrating payment in an existent php application

### ISSUE THREAD

**Issue by alexbohariuc** [braintree/braintree_php_example#49]
I’m trying to integrate the payment system in a Wordpress theme. So far, so good - we developed everything and on the local sandbox server (localhost:3000) it all works fine. 

My question is: 

How should eveything work when i’m going to integrate this in a Wordpress theme, on a shared hosting, how should the server be started? Is this possible? Should i simply use the files in public_html?

Thanks in advance!

**Comment by crookedneighbor** [comment]
If you're using Wordpress, then Wordpress takes care of starting the server for you.

You'd add the code to either your Wordpress theme or a plugin and use the Wordpress API to access them.
