### ISSUE TITLE
Drop-In ui: How to pre-select a payment method based on a vaulted payment method token?

### ISSUE THREAD

**Issue by rparsi-boxycharm** [braintree/braintree_php_example#51]
### General information

* Environment: 
Sandbox but functionality desired for Production as well
* Language, language version, and OS: 
Latest PHP SDK (integrated with magento via Braintree module)
### Issue description

I've read through and researched this topic in depth without finding a clear answer in braintree official docs or elsewhere.

The scenario is as follows:
Before the braintree PayPalCheckout js component is loaded, in our system we already have a saved vaulted payment method token.  When the Drop-In ui loads, after customer logs into their PayPal account we want the payment method associated with the saved token to be already selected.

How to do this?
Any help would be greatly appreciated.

**Comment by rparsi-boxycharm** [comment]
@crookedneighbor Hi, do you happen to work for Braintree?  Do you know how to implement the above described behavior (make a specific payment pre-selected in Drop-In ui based on vaulted payment token)?

**Comment by hollabaq86** [comment]
👋 @rparsi-boxycharm, please [contact Support](https://help.braintreepayments.com/) for assistance. GH issues are for bugs within this sample integration only.
