### ISSUE TITLE
I have tried this example and its working fine for credit card and paypal but it is not working for apple pay or google pay etc... how to enable it?

### ISSUE THREAD

**Issue by harshal-patel2110** [braintree/braintree_php_example#53]
### General information

* Environment: 
* Language, language version, and OS:

**Comment by harshal-patel2110** [comment]
I have tried this example and its working fine for credit card and paypal but it is not working for apple pay or google pay etc... how to enable it? #53

I have created key from apple developer account and uploaded to braintree sandbox and vice versa.

Even I am trying the example on https domain then also it is not showing option of apple pay, google pay etc...

It is only showing option of credit card and paypal.

**Comment by crookedneighbor** [comment]
Reach out to our support team for help with your integration. https://help.braintreepayments.com/
