### ISSUE TITLE
Integration Error: Detected a 3DS 1.0 Form POST to a 3DS 2.0 Endpoint 

### ISSUE THREAD

**Issue by anardil** [braintree/braintree_php_example#54]
### General information

* Environment: Sandbox
* Language, language version, and OS: PHP 7.3 on Ubuntu 18.10 

### Issue description

When I activate the 3DSecure, I've got a popup on screen with the error
**Integration Error: Detected a 3DS 1.0 Form POST to a 3DS 2.0 Endpoint** 

You have to use this credit cart number : 4000000000001091

Can you help me please?

Thank you.

**Comment by crookedneighbor** [comment]
Please reach out to our support team for this: https://developer.paypal.com/braintree/help/
