### ISSUE TITLE
paypal onPaymentMethodReceived

### ISSUE THREAD

**Issue by perlsol** [braintree/braintree_php_example#61]
with this example both CC and payapal are presented in the dropin, when using credit card the form can be submitted with this method...
  // Add the nonce to the form and submit
              document.querySelector('#nonce').value = payload.nonce;
              form.submit();

When using paypal, user is presented with the green tick once they have completed the paypal payment, but how can the form then be auto submitted, I read of onPaymentMethodReceived() but where to add this?

this didn't work either

onApprove: function (data, actions) {
          return paypalCheckoutInstance.tokenizePayment(data, function (err, payload) {
            // Submit 'payload.nonce' to your server
          });
        },

**Comment by hollabaq86** [comment]
👋 please contact [Technical Support](https://developer.paypal.com/braintree/help/) who can help you with this.
