### ISSUE TITLE
Braintree.js CDN link loading 2.15.5

### ISSUE THREAD

**Issue by ksherman** [braintree/braintree_php_example#8]
Howdy!

The braintree.js being loaded from the CDN is loading 2.15.5:
https://github.com/braintree/braintree_php_example/blob/master/public_html/index.php#L38

This specifically causes issues when trying to integrate AFT/Kount Device Data as it required 2.16+

Does it make sense for the example integrations to load a newer JS SDK v2 similar to our hello-client guide? https://developers.braintreepayments.com/start/hello-client/javascript/v2#setup

Thanks

**Comment by pblesi** [comment]
@ksherman Thank you for pointing this out. We are aware of this issue and are prioritizing work to address this. We will update this issue once these changes have been rolled out.

**Comment by danakatz** [comment]
Hi @ksherman,

After further discussion, we've decided that it's not practical to maintain specific JavaScript SDK versions across each of our example apps. Thanks again for bringing this to our attention.
